interface LoginEmailResponse {
  createTime: number
  avatar: string
  accessToken: string
  userId: number
  email: string
}

// Generated by https://quicktype.io

interface InfoSetResponse {
  amountExchangeCurrency: string
  safePassword: string
  auth: string
  mobile: string
  language: string
  theme: string
  email: string
}

// Generated by https://quicktype.io

interface IGamePageRes {
  score: number
  titleEn: string
  issueTime: number
  titleCn: string
  coverImage: string
  id: number
  titleTw: string
  tags: Tag[]
}

interface Tag {
  tw: string
  en: string
  cn: string
}
