interface LoginEmailResponse {
  createTime: number
  avatar: string
  accessToken: string
  userId: number
  email: string
}

// Generated by https://quicktype.io

interface InfoSetResponse {
  amountExchangeCurrency?: string
  safePassword?: string
  auth?: string
  mobile?: string
  language?: string
  theme?: string
  email?: string
  mobile: string
}

// Generated by https://quicktype.io

interface IGamePageRes {
  score: number
  titleEn: string
  issueTime: number
  titleCn: string
  coverImage: string
  id: number
  titleTw: string
  tags: Tag[]
}

interface Tag {
  tw: string
  en: string
  cn: string
}

// Generated by https://quicktype.io

interface ICoinChainlist {
  coinType: number
  chainScanUrl: string
  nameTw: string
  chainRealId: number
  chainId: number
  chainScanUrlPre: string
  icon: string
  nameCn: string
  nameEn: string
  url: string
  status: number
}
// Generated by https://quicktype.io

interface ICollectionPage {
  name: string
  id: number
}

interface ICollectionAddQ {
  name: string
}

// Generated by https://quicktype.io

interface ILoginSuccessRes {
  createTime?: number
  countryCode?: number
  mobile: string
  avatar?: string
  accessToken?: string
  userId?: number
}
