// Generated by https://quicktype.io
interface ICheckArt {
    artCount:     number;
    chainId:      number;
    gas:          number;
    name:         string;
    description:  string;
    currencyId:   number;
    collectionId: number;
    userId:       number;
    url:          string;
}

interface ICreateArt extends ICheckArt {
    safePassword: string;
}
