interface ResType<T> {
  // trace_id: string;
  code: number
  data: T
  success: boolean
  message?: string
  trace_id?: string
  page?: PageClass
}
type CodeResult = <T>(params: {
  res: ResType<T>
  success: (data: T, page: PageClass | undefined) => void
  error?: (data: T) => void
}) => null|T

// Generated by https://quicktype.io

interface PageClass {
  startRow: number
  navigatepageNums: number[]
  lastPage: boolean
  prePage: number
  hasNextPage: boolean
  nextPage: number
  pageSize: number
  endRow: number
  navigatePages: number
  total: number
  navigateFirstPage: number
  pages: number
  size: number
  firstPage: boolean
  hasPreviousPage: boolean
  navigateLastPage: number
}
